version: "3.7"

services:
   database_meritt:
      image: postgres
      container_name: database_meritt
      restart: always
      ports: 
         - 5433:5433
      environment: 
         - POSTGRES_USER=meritt
         - POSTGRES_PASSWORD=meritt123
         - POSTGRES_DB=meritt
      volumes: 
         - pgdata:/data/postgres
      network_mode: "bridge"
   app:
      build: .
      container_name: meritt
      ports:
         - 3333:3333
      volumes:
         - .:/usr/app
      network_mode: "bridge"


volumes: 
   pgdata:
      driver: local